# Generated by Django 3.2.2 on 2021-05-07 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catagories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagorie_name', models.CharField(max_length=100, verbose_name='catagorie')),
            ],
            options={
                'verbose_name_plural': 'catagoires',
                'db_table': 'catagoires',
            },
        ),
        migrations.CreateModel(
            name='show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_name', models.CharField(db_column='show_name', max_length=100, verbose_name='show name')),
                ('show_upload_date', models.DateField(auto_now_add=True, verbose_name='upload date')),
                ('show_title', models.CharField(db_column='show_title', max_length=100, verbose_name='show title')),
                ('show_description', models.CharField(db_column='show_description', max_length=100, verbose_name='show description')),
                ('show_caption', models.ImageField(upload_to='shows', verbose_name='show caption')),
                ('show_vedio', models.FileField(upload_to='vedio', verbose_name='show vedio')),
                ('show_catagory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='catagory_related', related_query_name='query_catagory', to='shows.catagories', verbose_name='catagory')),
            ],
            options={
                'verbose_name_plural': 'show',
                'db_table': 'show_table',
                'get_latest_by': ['-show_upload_date'],
            },
        ),
    ]
