# Generated by Django 3.2.2 on 2021-05-08 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shows', '0002_auto_20210508_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='show_authors',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
