# Generated by Django 3.2.2 on 2021-05-11 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shows', '0006_alter_show_show_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagories',
            name='catagorie_name',
            field=models.CharField(max_length=100, verbose_name='catagorie'),
        ),
        migrations.CreateModel(
            name='watch_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history_related', related_query_name='history_query', to=settings.AUTH_USER_MODEL)),
                ('waths', models.ManyToManyField(to='shows.show')),
            ],
        ),
    ]
