# Generated by Django 3.2.2 on 2021-05-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0007_auto_20210511_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch_history',
            name='waths',
            field=models.ManyToManyField(related_name='show_many', to='shows.show'),
        ),
    ]
